version: '3.8'

services:
  # Servicio de autenticación
  auth-service:
    image: node:16
    container_name: auth-service-container
    working_dir: /app
    volumes:
      - ./auth-service:/app
    networks:
      - app-network
    command: node index.js

  # Servicio del primer servidor backend (API)
  server1:
    image: node:16
    container_name: server1-container
    working_dir: /app
    volumes:
      - ./server1:/app
    networks:
      - app-network
    command: node index.js

  # Servicio del segundo servidor backend (Media)
  server2:
    image: node:16
    container_name: server2-container
    working_dir: /app
    volumes:
      - ./server2:/app
    networks:
      - app-network
    command: node index.js

  # Servicio del cliente (frontend)
  client:
    image: nginx:alpine
    container_name: client-container
    volumes:
      - ./client/dist:/usr/share/nginx/html
    networks:
      - app-network

  # Servicio del reverse proxy
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy-container
    ports:
      - "80:80"  # Expone el puerto 80 del reverse proxy
      - "443:443" # Expone el puerto 443 para HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs  # Certificados SSL
    depends_on:
      - client
      - auth-service
      - server1
      - server2
    networks:
      - app-network

# Define la red común
networks:
  app-network:
    driver: bridge